[package]
name = "fokus"
version = "2.0.1"
edition = "2024"

[dependencies]
ratatui = "0.28.0"
crossterm = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
dirs-next = "2.0.0"
toml = "0.9.5"
chrono = "0.4.41"
